// GENERATED by scripts/derive-chart.mjs -- do not edit by hand.
// Source: public/assets/audio/molam.mp3 at 107.07 BPM, first downbeat 0.247s.
// Re-run: npm run derive
import type { PatternEvent } from '../types';
import type { Difficulty } from '../../game/Difficulty';

export const bars = 41;

export const charts: Record<Difficulty, PatternEvent[]> = {
  "easy": [
    {
      "bar": 2,
      "beat": 0,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 2,
      "beat": 0.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 2,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 2,
      "beat": 1.5,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 2,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 2,
      "beat": 3.25,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 3,
      "beat": 0,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 3,
      "beat": 0.5,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 3,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 3,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 3,
      "beat": 2,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 3,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 3,
      "beat": 3.25,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 3,
      "beat": 3.5,
      "lane": 2,
      "voice": "phin",
      "midi": 64
    },
    {
      "bar": 4,
      "beat": 0,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 4,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 4,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 4,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 4,
      "beat": 3.25,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 5,
      "beat": 0,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 5,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 5,
      "beat": 1.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 60
    },
    {
      "bar": 6,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 6,
      "beat": 2.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 60
    },
    {
      "bar": 7,
      "beat": 0.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 7,
      "beat": 1.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 8,
      "beat": 1.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 15,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 18,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 18,
      "beat": 2,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 18,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 18,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 19,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 19,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 19,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 19,
      "beat": 1,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 19,
      "beat": 1.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 19,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 19,
      "beat": 3,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 20,
      "beat": 3,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 20,
      "beat": 3.5,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 21,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 21,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 21,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 21,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 22,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 22,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 22,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 22,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 23,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 23,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 23,
      "beat": 1,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 23,
      "beat": 2,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 23,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 23,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 24,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 24,
      "beat": 0,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 24,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 24,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 24,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 24,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 24,
      "beat": 3,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 25,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 60
    },
    {
      "bar": 25,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 25,
      "beat": 1,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 25,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 25,
      "beat": 3.5,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 26,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 26,
      "beat": 2,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 26,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 26,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 27,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 27,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 64
    },
    {
      "bar": 27,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 27,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 27,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 27,
      "beat": 3.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 28,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 28,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 28,
      "beat": 0.5,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 28,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 28,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 28,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 28,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 29,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 29,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 29,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 29,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 29,
      "beat": 2,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 29,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 29,
      "beat": 3,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 29,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 30,
      "beat": 0,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 30,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 30,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 30,
      "beat": 1,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 31,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 31,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 31,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 31,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 31,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 32,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 32,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 64
    },
    {
      "bar": 32,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 32,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 33,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 33,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 33,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 33,
      "beat": 2,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 33,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 33,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 33,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 34,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 34,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 34,
      "beat": 0.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 34,
      "beat": 1,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 35,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 37,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    }
  ],
  "normal": [
    {
      "bar": 2,
      "beat": 0,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 2,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 2,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 2,
      "beat": 1,
      "lane": 2,
      "voice": "phin",
      "midi": 62
    },
    {
      "bar": 2,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 2,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 2,
      "beat": 2,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 2,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 2,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 2,
      "beat": 3.25,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 3,
      "beat": 0,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 3,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 3,
      "beat": 0.5,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 3,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 3,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 3,
      "beat": 2,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 3,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 3,
      "beat": 3.25,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 4,
      "beat": 0,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 4,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 4,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 4,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 4,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 4,
      "beat": 3.25,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 5,
      "beat": 0,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 5,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 5,
      "beat": 1.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 60
    },
    {
      "bar": 5,
      "beat": 2.75,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 5,
      "beat": 3.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 6,
      "beat": 0.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 6,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 6,
      "beat": 1.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 6,
      "beat": 1.75,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 6,
      "beat": 2.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 60
    },
    {
      "bar": 6,
      "beat": 3.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 7,
      "beat": 0.25,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 7,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 7,
      "beat": 0.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 7,
      "beat": 1.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 7,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 7,
      "beat": 3.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 60
    },
    {
      "bar": 7,
      "beat": 3.5,
      "lane": 2,
      "voice": "phin",
      "midi": 62
    },
    {
      "bar": 8,
      "beat": 1,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 8,
      "beat": 1.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 8,
      "beat": 1.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 8,
      "beat": 3,
      "lane": 1,
      "voice": "ponglang",
      "midi": 60
    },
    {
      "bar": 10,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 10,
      "beat": 1.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 10,
      "beat": 3.75,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 11,
      "beat": 0.25,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 11,
      "beat": 1,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 11,
      "beat": 1.75,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 11,
      "beat": 3.75,
      "lane": 2,
      "voice": "phin",
      "midi": 62
    },
    {
      "bar": 12,
      "beat": 1.75,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 12,
      "beat": 3.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 13,
      "beat": 1.25,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 13,
      "beat": 1.75,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 13,
      "beat": 2.75,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 14,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 15,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 16,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 17,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 17,
      "beat": 1,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 17,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 17,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 18,
      "beat": 0,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 18,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 18,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 18,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 18,
      "beat": 2,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 18,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 18,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 18,
      "beat": 3,
      "lane": 1,
      "voice": "ponglang",
      "midi": 60
    },
    {
      "bar": 18,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 19,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 19,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 19,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 19,
      "beat": 1,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 19,
      "beat": 1.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 19,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 19,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 19,
      "beat": 3,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 19,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 20,
      "beat": 0,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 20,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 20,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 20,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 20,
      "beat": 1.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 20,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 20,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 20,
      "beat": 3,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 20,
      "beat": 3.5,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 20,
      "beat": 3.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 21,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 21,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 62
    },
    {
      "bar": 21,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 21,
      "beat": 1,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 21,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 21,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 21,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 21,
      "beat": 2.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 21,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 21,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 21,
      "beat": 3.75,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 22,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 22,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 64
    },
    {
      "bar": 22,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 22,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 22,
      "beat": 1.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 22,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 22,
      "beat": 2.5,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 22,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 22,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 23,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 23,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 23,
      "beat": 0.25,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 23,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 23,
      "beat": 1,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 23,
      "beat": 1.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 23,
      "beat": 2,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 23,
      "beat": 2.5,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 23,
      "beat": 2.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 23,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 23,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 24,
      "beat": 0,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 24,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 24,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 24,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 24,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 24,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 24,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 24,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 24,
      "beat": 3,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 24,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 24,
      "beat": 3.75,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 25,
      "beat": 0,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 25,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 25,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 25,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 25,
      "beat": 1,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 25,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 25,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 25,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 25,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 25,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 26,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 26,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 62
    },
    {
      "bar": 26,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 26,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 26,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 26,
      "beat": 2,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 26,
      "beat": 2.5,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 26,
      "beat": 2.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 26,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 26,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 27,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 64
    },
    {
      "bar": 27,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 27,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 27,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 27,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 27,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 27,
      "beat": 3.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 28,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 28,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 28,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 28,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 28,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 28,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 28,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 28,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 28,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 29,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 29,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 29,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 29,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 29,
      "beat": 2,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 29,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 29,
      "beat": 3,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 29,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 30,
      "beat": 0,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 30,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 30,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 30,
      "beat": 1,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 30,
      "beat": 2,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 30,
      "beat": 2.25,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 30,
      "beat": 2.5,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 30,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 30,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 31,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 31,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 31,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 31,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 31,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 31,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 31,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 31,
      "beat": 3.25,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 31,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 32,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 32,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 64
    },
    {
      "bar": 32,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 32,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 32,
      "beat": 2,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 32,
      "beat": 2.5,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 32,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 33,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 33,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 33,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 33,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 33,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 33,
      "beat": 2,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 33,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 33,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 33,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 34,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 34,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 34,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 34,
      "beat": 1,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 34,
      "beat": 2.25,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 34,
      "beat": 2.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 34,
      "beat": 3,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 34,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 34,
      "beat": 3.75,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 35,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 35,
      "beat": 2.5,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 35,
      "beat": 2.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 36,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 37,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 38,
      "beat": 0.75,
      "lane": 2,
      "voice": "phin",
      "midi": 62
    },
    {
      "bar": 38,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    }
  ],
  "hard": [
    {
      "bar": 2,
      "beat": 0,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 2,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 2,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 2,
      "beat": 1,
      "lane": 2,
      "voice": "phin",
      "midi": 62
    },
    {
      "bar": 2,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 2,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 2,
      "beat": 1.75,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 2,
      "beat": 2,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 2,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 2,
      "beat": 2.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 2,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 2,
      "beat": 3.25,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 3,
      "beat": 0,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 3,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 3,
      "beat": 0.5,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 3,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 3,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 3,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 3,
      "beat": 2,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 3,
      "beat": 2.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 3,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 3,
      "beat": 3.25,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 4,
      "beat": 0,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 4,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 4,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 4,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 4,
      "beat": 1.75,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 4,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 4,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 4,
      "beat": 3.25,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 5,
      "beat": 0,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 5,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 60
    },
    {
      "bar": 5,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 5,
      "beat": 1.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 60
    },
    {
      "bar": 5,
      "beat": 2,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 5,
      "beat": 2.75,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 5,
      "beat": 3.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 6,
      "beat": 0.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 6,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 6,
      "beat": 1.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 6,
      "beat": 1.75,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 6,
      "beat": 2.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 60
    },
    {
      "bar": 6,
      "beat": 2.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 6,
      "beat": 3.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 7,
      "beat": 0.25,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 7,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 7,
      "beat": 0.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 7,
      "beat": 1.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 7,
      "beat": 1.5,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 7,
      "beat": 1.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 7,
      "beat": 2.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 7,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 7,
      "beat": 3.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 60
    },
    {
      "bar": 7,
      "beat": 3.5,
      "lane": 2,
      "voice": "phin",
      "midi": 62
    },
    {
      "bar": 8,
      "beat": 0,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 8,
      "beat": 0.25,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 8,
      "beat": 1,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 8,
      "beat": 1.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 8,
      "beat": 1.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 8,
      "beat": 3,
      "lane": 1,
      "voice": "ponglang",
      "midi": 60
    },
    {
      "bar": 9,
      "beat": 1.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 9,
      "beat": 2.75,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 10,
      "beat": 0.25,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 10,
      "beat": 0.5,
      "lane": 2,
      "voice": "phin",
      "midi": 64
    },
    {
      "bar": 10,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 10,
      "beat": 1.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 10,
      "beat": 1.75,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 10,
      "beat": 2.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 10,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 10,
      "beat": 3.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 10,
      "beat": 3.75,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 11,
      "beat": 0.25,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 11,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 11,
      "beat": 1.75,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 11,
      "beat": 3.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 12,
      "beat": 0.25,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 12,
      "beat": 1.75,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 12,
      "beat": 3.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 13,
      "beat": 0.25,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 13,
      "beat": 1.25,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 13,
      "beat": 1.75,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 13,
      "beat": 2.75,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 13,
      "beat": 3.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 14,
      "beat": 0.25,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 14,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 14,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 15,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 15,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 15,
      "beat": 1.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 15,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 16,
      "beat": 0,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 16,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 16,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 16,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 16,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 16,
      "beat": 3.25,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 16,
      "beat": 3.5,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 17,
      "beat": 0,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 17,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 64
    },
    {
      "bar": 17,
      "beat": 0.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 17,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 17,
      "beat": 1,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 17,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 17,
      "beat": 1.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 17,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 17,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 17,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 18,
      "beat": 0,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 18,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 18,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 18,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 18,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 18,
      "beat": 2,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 18,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 18,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 18,
      "beat": 3,
      "lane": 1,
      "voice": "ponglang",
      "midi": 60
    },
    {
      "bar": 18,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 19,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 19,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 19,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 19,
      "beat": 1,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 19,
      "beat": 1.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 19,
      "beat": 2.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 19,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 19,
      "beat": 2.75,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 19,
      "beat": 3,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 19,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 20,
      "beat": 0,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 20,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 20,
      "beat": 0.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 20,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 20,
      "beat": 0.75,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 20,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 20,
      "beat": 1.25,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 20,
      "beat": 1.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 20,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 20,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 20,
      "beat": 3,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 20,
      "beat": 3.5,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 20,
      "beat": 3.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 21,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 62
    },
    {
      "bar": 21,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 21,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 21,
      "beat": 1,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 21,
      "beat": 1.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 21,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 21,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 21,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 21,
      "beat": 2.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 21,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 21,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 21,
      "beat": 3.75,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 22,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 22,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 64
    },
    {
      "bar": 22,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 22,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 22,
      "beat": 1.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 22,
      "beat": 1.75,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 22,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 22,
      "beat": 2.5,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 22,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 22,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 23,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 23,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 23,
      "beat": 0.25,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 23,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 23,
      "beat": 1,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 23,
      "beat": 1.25,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 23,
      "beat": 1.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 23,
      "beat": 1.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 23,
      "beat": 2,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 23,
      "beat": 2.25,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 23,
      "beat": 2.5,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 23,
      "beat": 2.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 23,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 23,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 24,
      "beat": 0,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 24,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 24,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 24,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 24,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 24,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 24,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 24,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 24,
      "beat": 3,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 24,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 24,
      "beat": 3.75,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 25,
      "beat": 0,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 25,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 25,
      "beat": 0.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 25,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 25,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 25,
      "beat": 1,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 25,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 25,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 25,
      "beat": 1.75,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 25,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 25,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 25,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 25,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 25,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 25,
      "beat": 3.75,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 26,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 26,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 62
    },
    {
      "bar": 26,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 26,
      "beat": 0.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 26,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 26,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 26,
      "beat": 2,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 26,
      "beat": 2.5,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 26,
      "beat": 2.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 26,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 26,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 27,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 64
    },
    {
      "bar": 27,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 27,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 27,
      "beat": 0.75,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 27,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 27,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 27,
      "beat": 1.75,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 27,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 27,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 27,
      "beat": 3.5,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 27,
      "beat": 3.75,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 28,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 28,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 28,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 28,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 28,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 28,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 28,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 28,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 28,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 29,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 29,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 29,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 29,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 29,
      "beat": 2,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 29,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 29,
      "beat": 3,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 29,
      "beat": 3.25,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 29,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 30,
      "beat": 0,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 30,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 30,
      "beat": 0.25,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 30,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 30,
      "beat": 1,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 30,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 30,
      "beat": 2,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 30,
      "beat": 2.25,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 30,
      "beat": 2.5,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 30,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 30,
      "beat": 3.25,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 30,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 31,
      "beat": 0,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 31,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 31,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 31,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 31,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    },
    {
      "bar": 31,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 31,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 31,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 31,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 31,
      "beat": 3.25,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 31,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 32,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 64
    },
    {
      "bar": 32,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 64
    },
    {
      "bar": 32,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 32,
      "beat": 0.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 60
    },
    {
      "bar": 32,
      "beat": 1,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 32,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 32,
      "beat": 2,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 32,
      "beat": 2.5,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 32,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 32,
      "beat": 3.75,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 33,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 67
    },
    {
      "bar": 33,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 33,
      "beat": 0.5,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 33,
      "beat": 0.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 33,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 33,
      "beat": 1.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 33,
      "beat": 2,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 33,
      "beat": 2.25,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 33,
      "beat": 2.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 33,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 33,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 33,
      "beat": 3.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 34,
      "beat": 0,
      "lane": 1,
      "voice": "ponglang",
      "midi": 69
    },
    {
      "bar": 34,
      "beat": 0,
      "lane": 2,
      "voice": "phin",
      "midi": 69
    },
    {
      "bar": 34,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 34,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 34,
      "beat": 1,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 34,
      "beat": 2.25,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 34,
      "beat": 2.5,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 34,
      "beat": 3,
      "lane": 1,
      "voice": "ponglang",
      "midi": 62
    },
    {
      "bar": 34,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 35,
      "beat": 1.25,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 35,
      "beat": 2,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 35,
      "beat": 2.5,
      "lane": 2,
      "voice": "phin",
      "midi": 60
    },
    {
      "bar": 35,
      "beat": 2.75,
      "lane": 3,
      "voice": "khaen",
      "midi": 62
    },
    {
      "bar": 35,
      "beat": 3.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 35,
      "beat": 3.75,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 36,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 67
    },
    {
      "bar": 36,
      "beat": 1.75,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 36,
      "beat": 3,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 36,
      "beat": 3.75,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 37,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 69
    },
    {
      "bar": 37,
      "beat": 0.75,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 37,
      "beat": 1.5,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 37,
      "beat": 2.75,
      "lane": 2,
      "voice": "phin",
      "midi": 67
    },
    {
      "bar": 37,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 37,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 38,
      "beat": 0,
      "lane": 0,
      "voice": "klong",
      "midi": 67
    },
    {
      "bar": 38,
      "beat": 0.75,
      "lane": 2,
      "voice": "phin",
      "midi": 62
    },
    {
      "bar": 38,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 60
    },
    {
      "bar": 38,
      "beat": 3.5,
      "lane": 0,
      "voice": "klong",
      "midi": 64
    },
    {
      "bar": 39,
      "beat": 3,
      "lane": 0,
      "voice": "klong",
      "midi": 62
    },
    {
      "bar": 39,
      "beat": 3.75,
      "lane": 0,
      "voice": "klong",
      "midi": 69
    },
    {
      "bar": 40,
      "beat": 0.5,
      "lane": 3,
      "voice": "khaen",
      "midi": 64
    }
  ]
};
